[package]
name = "sleep-training-timer"
version = "0.1.0"
authors = ["Jackson Egan"]

[dependencies]
tokio-timer = "0.1"
tokio = "0.1"
futures = "0.1"
time = "0.1"
clap = "2"
indicatif = "0.9.0"
console = "0.6.1"

